FROM centos/devtoolset-4-toolchain-centos7
MAINTAINER Ben Shealy <btsheal@clemson.edu>

# install package dependencies
USER 0

RUN yum install -y epel-release make gperf bison flex mesa-libGL-devel openmpi-devel telnet wget \
	&& yum install -y clinfo ocl-icd-devel

ENV MPIDIR  "/usr/lib64/openmpi"
ENV PATH    "$MPIDIR/bin:$PATH"

# install Qt
RUN cd /opt \
	&& wget -q http://download.qt.io/official_releases/qt/5.11/5.11.1/single/qt-everywhere-src-5.11.1.tar.xz \
	&& tar -xf qt-everywhere-src-5.11.1.tar.xz \
	&& rm qt-everywhere-src-5.11.1.tar.xz \
	&& mkdir qt \
	&& cd qt \
	&& ../qt-everywhere-src-5.11.1/configure -prefix . -opensource -confirm-license \
	&& gmake -j 20 \
	&& gmake -j 20 install \
	&& rm -rf ../qt-everywhere-src-5.11.1

ENV QTDIR  "/opt/qt"
ENV PATH   "$QTDIR/bin:$PATH"

# install ACE
RUN cd /opt \
	&& git clone https://github.com/SystemsGenetics/ACE.git \
	&& cd ACE/build \
	&& git checkout develop \
	&& qmake ../src/ACE.pro PREFIX=/opt/ace \
	&& make -j 20 \
	&& make qmake_all \
	&& make install

ENV ACEDIR              "/opt/ace"
ENV PATH                "$ACEDIR/bin:$PATH"
ENV CPLUS_INCLUDE_PATH  "$ACEDIR/include:$CPLUS_INCLUDE_PATH"
ENV LIBRARY_PATH        "$ACEDIR/lib:$LIBRARY_PATH"
ENV LD_LIBRARY_PATH     "$ACEDIR/lib:$LD_LIBRARY_PATH"

# install KINC
RUN cd /opt \
	&& git clone https://github.com/SystemsGenetics/KINC.git \
	&& cd KINC/build \
	&& git checkout develop \
	&& qmake ../src/KINC.pro PREFIX=/opt/kinc \
	&& make -j 20 \
	&& make qmake_all \
	&& make install

ENV KINCDIR  "/opt/kinc"
ENV PATH     "$KINCDIR/bin:$PATH"
